### ISSUE TITLE
Small error in "What is API Mocking?" article

### ISSUE THREAD

**Issue by headexpanded** [mockoon/mockoon.com#107]
Me again :)

In the https://mockoon.com/articles/what-is-api-mocking/ article, the sub-heading "How does API mocking works?" should be "How does API mocking work?"

(no 's' on work)

Also, in the FAQ https://mockoon.com/faq/ , "How does Mockoon mock API creation works?" - same as above, no 's' on 'works'

**Comment by 255kb** [comment]
Damned!
I proofread everything. Surely someone is adding typos behind my back 🙈
