### ISSUE TITLE
English documentation fix-ups 

### ISSUE THREAD

**Issue by markhatherly** [mockoon/mockoon.com#119]
Hi Guillaume, I installed Mockoon here at work and it's great! In reading the docs more thoroughly I found some fix-ups:

https://mockoon.com/docs/latest/api-endpoints/routing/

**API routes -> Routes Order:** should be "This means that the first..."

https://mockoon.com/docs/latest/data-buckets/using-data-buckets/#using-data-helpers

**Referencing in a route response:** should be "A data bucket can also..."

https://mockoon.com/docs/latest/templating/mockoon-helpers/#data

**dataRaw -> table -> 1st row -> Description:** should be: "ID or name of the data bucket"

https://mockoon.com/docs/latest/api-endpoints/crud-routes/

**List of routes and operations ->  Note:**
should be "...sending the same type of content as the one stored..."
should be "...ending up with mixed type contents..."

**Comment by 255kb** [comment]
Hi Mark! 
Thank you, it's deploying now. 
It seems the more I proofread, the more typos there are 🤪
