### ISSUE TITLE
i am not getting example environment in mockoon.

### ISSUE THREAD

**Issue by neelamaryabitvivid** [mockoon/mockoon.com#12]
Earlier mockoon default environment that is example environment was showing on mockoon but now it is not showing.

**Comment by 255kb** [comment]
I cannot reproduce this problem. 
If I install Mockoon latest version (fresh setup, no user settings) I got the "Example" environment on startup. 
Please note that if you delete this environment, or if you modify it there is no way to get it back unless by deleting the user settings folder and restart the application (but you will lose all your other environments)
