### ISSUE TITLE
Print form-data from Postman

### ISSUE THREAD

**Issue by yoviprasetyo** [mockoon/mockoon.com#39]
I want to simulate an upload file in Mockoon.
The `body` in the [docs](https://mockoon.com/docs/latest/templating/):
> get the value at a given path from the request body if the entering Content-Type is set to application/json or application/x-www-form-urlencoded

I use Postman as the client. But Mockoon can't print what I send. I need form-data to simulate upload file.
In the Postman uploading file can be done just use form-data. However, the content of form-data is recorded if I print {{ body }}.
I wonder if Mockoon can simulate upload file use form-data instead.

**Comment by 255kb** [comment]
Hi @yoviprasetyo Thank you for opening this issue. 
However, this is the wrong repository (website vs project). Could you please move it to this repository https://github.com/mockoon/mockoon/issues and follow the issue template? Thank you :)
