### ISSUE TITLE
Typo in the closing tags for the switch case helper 

### ISSUE THREAD

**Issue by Kalli** [mockoon/mockoon.com#90]
Hey there 👋 First of thanks for a great tool. Happy Mockoon user, it has been very useful to me!

**Describe the bug**

A typo in the documentation for [the `switch` helper](https://mockoon.com/docs/latest/templating/mockoon-helpers/#switch) means that the provided example does not work as is. I believe the closing tag needs to be changed from `{{# /}}` to `{{/ switch}}`

Screenshot of docs (note that the closing tag does not match opening tag):

![image](https://user-images.githubusercontent.com/465566/160634790-e91f6f6c-7c1b-4713-bc03-ceb7189b0fd8.png)

**To Reproduce**

* Copy paste the example from the docs into a route in Mockoon
* Visit/curl the route. You should get an error: 
    
   ```
   Error while serving the content: Parse error on line 5:..."{{/ default }}{{# /}}
    ----------------------^
   Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'SEP' 
   ```
* Tested in Mockoon 1.18.1
 
**Expected behavior**

* I expected the example to work if copied verbatim. 

PR with fix incoming in a minute!

**Comment by 255kb** [comment]
Thank you for spotting this and for the PR! 
Also, you could receive the award of the "Very Best Issue Report" 💪
So, thank you for following the template, and providing that much information for such a small fix, I really appreciate it!

**Comment by Kalli** [comment]
>Also, you could receive the award of the "Very Best Issue Report" 💪

😄 Thank you for the kind words and the swift turnaround on the issue. Happy to contribute (however minorly). Keep up the great work with Mockoon, again great tool, has been very helpful!
